### ISSUE TITLE
Set InitialBlock=0

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-erc20-supply#3]
When calling `make info` it shows **Initial block: 1397553**

- [ ] Set InitialBlock=0
  - [ ] erc20-supply
  - [ ] erc20-contract-info

```yaml
make info
substreams info
Package name: erc20_supply
Version: v0.1.0
Doc: ERC-20 Token Supply
Modules:
----
Name: map_balance_changes
Initial block: 0
Kind: map
Output Type: proto:erc20.types.v1.BalanceChanges
Hash: 5b0bcc0bd04653f0b398b3e34fb4cf9fcb8ef148
Doc: Extracts ERC20 balance changes

Name: map_valid_balance_changes
Initial block: 0
Kind: map
Output Type: proto:erc20.types.v1.ValidBalanceChanges
Hash: 68b78a7f5b8c554468a236191c33fdf8dedc3810
Doc: Extracts ERC20 balance changes

Name: map_token_supply
Initial block: 0
Kind: map
Output Type: proto:erc20.supply.types.v1.TotalSupplies
Hash: aece54b8435b37d2565b54f54d2a185a38ec9460
Doc: Extracts ERC20 token total supply

Name: graph_out
Initial block: 0
Kind: map
Output Type: proto:sf.substreams.sink.entity.v1.EntityChanges
Hash: abbce463fe542510df4030b10e1559fa2082864a

Name: balance_changes:map_balance_changes
Initial block: 1397553
Kind: map
Output Type: proto:erc20.types.v1.BalanceChanges
Hash: 4e1ace7a8ce18ee7d18dee39016360eb28880491
Doc: Extracts ERC20 balance changes

Name: balance_changes:map_valid_balance_changes
Initial block: 1397553
Kind: map
Output Type: proto:erc20.types.v1.ValidBalanceChanges
Hash: a932056d8db1a50397f6500ef7e2442110bf0565
Doc: Extracts ERC20 balance changes

Name: balance_changes:map_unknown_balance_changes
Initial block: 1397553
Kind: map
Output Type: proto:erc20.types.v1.UnknownBalanceChanges
Hash: cf67264e04dd5903addeb278159c1a9c8bea52d4

Name: balance_changes:db_out
Initial block: 1397553
Kind: map
Output Type: proto:sf.substreams.sink.database.v1.DatabaseChanges
Hash: 6a17a67e2f38160723044c8ea99c120da725ddf1

Name: balance_changes:graph_out
Initial block: 1397553
Kind: map
Output Type: proto:sf.substreams.sink.entity.v1.EntityChanges
Hash: 3f917a2ae8396adc398567f11ae3233c112fc42f

Name: balance_changes:store_valid_balance_changes
Initial block: 1397553
Kind: store
Value Type: bigint
Update Policy: UPDATE_POLICY_ADD
Hash: fb58f909936d46ce7e488e90d29dae4cf1082679

Name: balance_changes:balance_change_stats
Initial block: 1397553
Kind: map
Output Type: proto:erc20.types.v1.BalanceChangeStats
Hash: 3d58500849c241dad9d5a9d5c1f5492763d16ed3
```
