### ISSUE TITLE
Include schema.sql with CREATE TABLE

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-erc20-supply#4]
### `schema.sql`

https://github.com/streamingfast/substreams-sink-sql/blob/develop/docs/tutorial/schema.sql

```sql
create table block_meta
(
    id          text not null constraint block_meta_pk primary key,
    at          timestamp,
    number      bigint,
    hash        text,
    parent_hash text,
    timestamp   timestamp
);

create table cursors
(
    id         text not null constraint cursor_pk primary key,
    cursor     text,
    block_num  bigint,
    block_id   text
);
```
## `substreams.yaml`

https://github.com/streamingfast/substreams-sink-sql/blob/6054492a4abc38f1eace54179080e19f9984b4dd/docs/tutorial/substreams.yaml#L36C1-L44C31

```
network: mainnet

sink:
  module: blockmeta:db_out
  type: sf.substreams.sink.sql.v1.Service
  config:
    schema: "./schema.sql"
    wire_protocol_access: true
```
